package gui;

import controller.Controller;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class LoginPanel {

    private JPanel mainPanel;
    private JTextField txtUsernameTextField;
    private JPasswordField txtPasswordPasswordField;
    private JButton btnloginButton;

    private Controller controller;
    private JFrame frame;

    public LoginPanel(Controller controller, JFrame frame) {
        this.controller = controller;
        this.frame = frame;

        // Ascoltatore reattivo associato al click del pulsante di login
        btnloginButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Estrazione del testo inserito dall'utente nei campi grafici
                String username = txtUsernameTextField.getText().trim();
                String password = new String(txtPasswordPasswordField.getPassword()).trim();

                // Validazione locale dell'input per impedire l'invio di stringhe vuote
                if (username.isEmpty() || password.isEmpty()) {
                    JOptionPane.showMessageDialog(frame, "Inserisci username e password!");
                    return;
                }

                // Inoltro delle credenziali al Controller
                String ruolo = controller.login(username, password);

                // Smistamento dei flussi di navigazione in base alla risposta del Controller
                if (ruolo.equals("admin")) {
                    JOptionPane.showMessageDialog(frame, "Benvenuto Admin: " + username);

                    // Creazione della cornice indipendente per l'area amministratore
                    JFrame adminFrame = new JFrame("Area Amministratore");
                    AdminPanel adminPanel = new AdminPanel(controller, adminFrame, frame);

                    // Impostazione della dimensione preferita di base per il pannello dell'amministratore
                    adminPanel.getMainPanel().setPreferredSize(new Dimension(600, 450));

                    // Configurazione del frame e passaggio del controllo visivo
                    adminFrame.setContentPane(adminPanel.getMainPanel());
                    adminFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    adminFrame.pack();
                    adminFrame.setLocationRelativeTo(frame);
                    adminFrame.setVisible(true);
                    frame.setVisible(false);

                } else if (ruolo.equals("medico")) {
                    JOptionPane.showMessageDialog(frame, "Benvenuto Medico: " + username);

                    // Creazione della cornice indipendente per l'area medica
                    JFrame medicoFrame = new JFrame("Area Medica");
                    MedicoPanel medicoPanel = new MedicoPanel(controller, medicoFrame, frame,username);

                    // Impostazione della dimensione preferita di base per il pannello del medico
                    medicoPanel.getMainPanel().setPreferredSize(new Dimension(600, 450));

                    // Configurazione del frame e passaggio del controllo visivo
                    medicoFrame.setContentPane(medicoPanel.getMainPanel());
                    medicoFrame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    medicoFrame.pack();
                    medicoFrame.setLocationRelativeTo(frame);
                    medicoFrame.setVisible(true);
                    frame.setVisible(false);

                } else {
                    // Feedback visivo di errore bloccante
                    JOptionPane.showMessageDialog(frame, "Username o password errati!",
                            "Errore", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    // Restituisce il pannello grafico principale per poterlo inserire all'interno della finestra (JFrame)
    public JPanel getMainPanel() {
        return mainPanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(5, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("password:");
        mainPanel.add(label1, new com.intellij.uiDesigner.core.GridConstraints(2, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtPasswordPasswordField = new JPasswordField();
        txtPasswordPasswordField.setText("");
        mainPanel.add(txtPasswordPasswordField, new com.intellij.uiDesigner.core.GridConstraints(3, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 30), new Dimension(150, -1), null, 0, false));
        btnloginButton = new JButton();
        btnloginButton.setText("Login");
        mainPanel.add(btnloginButton, new com.intellij.uiDesigner.core.GridConstraints(4, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final JLabel label2 = new JLabel();
        label2.setText("\tUsername\n");
        mainPanel.add(label2, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        txtUsernameTextField = new JTextField();
        txtUsernameTextField.setText("");
        mainPanel.add(txtUsernameTextField, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, new Dimension(150, 30), new Dimension(150, -1), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}